### ISSUE TITLE
Input validator

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1034]
In GitLab by @mkovari on Apr 6, 2020, 09:15

I think it might be good to create summary issues that bring together several smaller tasks.  As an example I have summarised the three issues that mention the input validator.  Future work on the input validator can be added to the bottom of the list.  (Or should we add it to the top of the list?)

* [x] Duplicate variable checking #996
* [x] Obsolete variable checker #1000
* [x] Move obsolete variable names into separate module #1004

Any comments @jonmaddock @jmorris-uk @stuartmuldrew?
