### ISSUE TITLE
Prepare for moving the module calls outside of the solver loop in subroutine vmcon

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1076]
@mkovari and @jonmaddock:
* [x] Jon: Get vmcon tests (currently a program in maths_library.f90) working (and passing) from pytest #1077 
* [x] Jon and Michael: Set up Michael with VS-Code-pytest environment
* [x] Jon and Michael: Fortran refactor: Refactor Fortran into smaller subroutines so that fcnvmc1 and 2 can be called from Python (with vmcon unit tests passing) #1078 
* [x] Jon: Python refactor to call fcnvmc1 and 2 #1079
