### ISSUE TITLE
Tracking for cost model

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1345]
In GitLab by @hlux on Jul 15, 2021, 13:51

## Summary

Can you please start tracking the cost model 2 variables in a tracker for the PROCESS Develop branch. Ideally, these should be all cost related variables entire account structure for capex and Levelise cost of electricity (LCOE), plus key parameters like Rmajor, Pfusion, Net electric.

Can this be run routinely on SPR1 to SPR 23?

@timothy-nunn , @jonmaddock suggested that you could take this task on. I expect that Jon can explain most of it to you. Anything that is unclear, please come back to me. Thanks!

## Checklist

After implementing issue do the following

* [x] Run test suite
* [x] Does it change the output? If so, give justifications.
* [x] Does it change the baseline 2019 run? (you may need to run on Freia)
* [x] Merge request created
