### ISSUE TITLE
Pipeline baseline failures

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1380]
In GitLab by @timothy-nunn on Aug 17, 2021, 11:00

## Summary

When running the pipeline for either benchmark 2018 or 2019, there is an error regarding missing variables. These errors are being caught and handled so it is unclear if the job is running successfully -- if not this could indicate that we have received false negatives (passes) from the baseline jobs. 

## Todo

- [x] Remove testing aspects of tracking baselines
- [x] Move baselines under tracking stage
- [x] Tracker only uses py38 so the only the py38 stages should be run
- [x] Tracker only runs on develop pipelines - make the baseline jobs the same

## Checklist

After fixing bug do the following

* [x] Run test suite
* [x] Does it change the output? If so, give justifications.
* [x] Does it change the baseline 2019 run? (you may need to run on Freia)
* [x] Merge request created
