### ISSUE TITLE
Commit message variable in tracker

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#1485]
In GitLab by @timothy-nunn on Nov 24, 2021, 08:53

- [x] Add commit hash
- [x] Fix commit name
- [x] Force x-axis to be date
- [x] Default commit hash as "-"
- [x] Do not cover lines with the legend
