### ISSUE TITLE
ndscan.py utility overhaul

### ISSUE THREAD

**Issue by jonmaddock** [ukaea/PROCESS#939]
In GitLab by @asbrown on Sep 30, 2019, 16:52

## Summary

This is a single point of contact for overhauling the ndscan.py utility that has a number of issues associated with it and all can be addressed at the same time:
* [ ] #289 - ndscan.py - smoothing in ND<br />
* [ ] #410 - New scan utility<br />
* [ ] #502 - Improvements to scan<br />
* [ ] #594 - N-dim scan not finding solutions and visualisation does not plot, for N = 1

## Checklist

After implementing issue do the following:
* [ ] Run test suite
* [ ] Does it change the output? If so, give justifications.
* [ ] Does it change the baseline 2019 run? (you may need to run on Freia)
* [ ] Merge request created
